### ISSUE TITLE
Constructor with trailing decimal zeros fails

### ISSUE THREAD

**Issue by zouppen** [peterolson/BigRational.js#13]
When creating `bigRat` using string which contain trailing zeros after decimal point, it fails:

```javascript
bigRat('2.0')
```

> Error: Invalid integer

On the contrary creating `bigRat` from decimal number without trailing zeros does work (e.g. *2.01*).

**Comment by peterolson** [comment]
Sorry for the delay. This seems to be fixed now, I can't reproduce the error. Let me know if the issue persists.
