### ISSUE TITLE
publish working version as 0.9.11 version

### ISSUE THREAD

**Issue by vschoettke** [peterolson/BigRational.js#16]
The problem with require and node was fixed, but was published as 0.10.0 version. So if anyone has still "^0.9.8" in their package.json they get the broken 0.9.10 version due to the semver handling for 0.x.x.

So please also push the the fix as 0.9.11

**Comment by peterolson** [comment]
Can you reproduce a problem based on this? I had already thought about this and published 0.9.11 before I published 0.10.0. Running

    npm view big-rational versions

lists 

     [ '0.9.0',
       '0.9.1',
       '0.9.2',
       '0.9.3',
       '0.9.4',
       '0.9.5',
       '0.9.6',
       '0.9.7',
       '0.9.8',
       '0.9.9',
       '0.9.10',
       '0.9.11',
       '0.10.0' ]

Does doing an `npm install` for a package depending on `"^0.9.8"` not install the `0.9.11` version?

**Comment by vschoettke** [comment]
Seems to work fine from home. Maybe it's a cache related issue. I'll try to find out what went wrong on Monday and close that bug for now.
