### ISSUE TITLE
ToDecimal(0)

### ISSUE THREAD

**Issue by pernas** [peterolson/BigRational.js#30]
when you execute toDecimal(0) it returns the default number of decimals instead of zero because `0 || whatever` always return `whatever`

It this intentional?

https://github.com/peterolson/BigRational.js/blob/8f8c2fade3b11faae7f452e215b183d7e48a53ac/BigRational.js#L160

**Comment by peterolson** [comment]
No, this is not intentional, thanks for pointing out the bug. I'll try to fix it soon

**Comment by peterolson** [comment]
This should be fixed now, thanks
