### ISSUE TITLE
better .valueOf()

### ISSUE THREAD

**Issue by grondilu** [peterolson/BigRational.js#31]
Hello,

if either this.num.valueOf() or this.denom.valueOf() is "infinity", then this.valueOf() will be NaN.   This can be avoided with something like:

    BigRational.prototype.valueOf = function () {
        const N = 1000000; // pick any large integer
        return this.multiply(N).floor().num / N;
    }

FYI this "issue" occurred with an experiment of mine : 
http://grondilu.github.io/rational-trackball.html

PS.  If I'm not mistaken, BigRational is encapsulated so it's not possible to override the valueOf method in user-space.  That's kind of a bummer, if you ask me.

**Comment by peterolson** [comment]
Thanks for reporting the issue. I've added a fix. Let me know if you encounter any more issues.
