### ISSUE TITLE
Why encapsulate the class?

### ISSUE THREAD

**Issue by grondilu** [peterolson/BigRational.js#33]
When I include the library, I can't use `instanceof` to test if an object is an instance of `BigRational` since that class is encapsulated.

Can't the library just export the class instead of just a constructor?

**Comment by peterolson** [comment]
If you need to use `instanceof` you could use the `constructor` property:
```
> bigRat(4) instanceof bigRat.one.constructor
// true
> new Date() instanceof bigRat.one.constructor
// false
```
