### ISSUE TITLE
hotlinkable illegal character

### ISSUE THREAD

**Issue by thecircleoflifefree** [peterolson/BigRational.js#36]
Issue:

When using the hotlinkable option:
Put following line on html document
<script src="http://peterolson.github.com/BigRational.js/BigInt_BigRat.min.js"></script> 

Tested as well: http://peterolson.github.io/BigRational.js/BigInt_BigRat.min.js

console returns: SyntaxError: illegal characterBigInt_BigRat.min.js:1:38714

![questionBigRationalJS](https://user-images.githubusercontent.com/26904626/72653783-2dfedb80-3952-11ea-99b7-42cb649432bd.png)
![responsepayload](https://user-images.githubusercontent.com/26904626/72653801-4a9b1380-3952-11ea-9367-a42e47da7c20.png)

Firefox version 68.0.1 (64bit) in linux machine

It looks like the last character ->   is the one affecting. Although even after removing it and using it locally in browser, still unable to use bigRat()

**Comment by peterolson** [comment]
Thanks, should be fixed now. Let me know if the issue persists for you.
